blank_issues_enabled: true
contact_links:
  - name: "ℹ️ Pioneer Manual (base game)"
    url: https://wiki.pioneerspacesim.net/wiki/Manual
    about: Manual for the base game. Casimir is an unofficial fork of Pioneer, so some things differ.
  - name: "🚀 Pioneer Flight Manual (base game)"
    url: https://wiki.pioneerspacesim.net/wiki/Basic_flight
    about: Manual for flying
